name: 'Saplings - Events'
description: 'Creates an Search Engine Optimized Event system.'
type: 'Site'
recipes:
  - events
  - events_calendar
  - events_locations
install:
  # Core.
  - image
  - link
  - link_attributes
  - media
  - node
  - options
  - taxonomy
  # Contrib.
  - access_unpublished
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - publication_date
  - quick_node_clone
  - schema_event
  - token
  - token_or
config:
  actions:
    # Set permissions for anonymous role.
    user.role.anonymous:
      createIfNotExists:
        id: anonymous
      grantPermissions:
        - 'access_unpublished node event'
    # Set permissions for content editor role.
    user.role.content_editor:
      createIfNotExists:
        id: content_editor
      grantPermissions:
        - 'access_unpublished node event'
        - 'clone event content'
        - 'create event content'
        - 'create terms in event_category'
        - 'delete own event content'
        - 'delete event revisions'
        - 'edit any event content'
        - 'edit own event content'
        - 'edit terms in event_category'
        - 'revert event revisions'
        - 'set event published on date'
        - 'view any unpublished event content'
        - 'view event revisions'
    #core.entity_view_display.node.event.default:
      #setComponents:
