name: 'Saplings - Events'
description: 'Configuration for Saplings Events'
type: 'Site'
recipes:
  - events
  - events_calendar
  - events_location
install:
  # Core.
  - image
  - link
  - link_attributes
  - media
  - node
  - options
  - taxonomy
  # Contrib.
  - access_unpublished
  - metatag
  - pathauto
  - publication_date
  - quick_node_clone
  - schema_event
config:
  actions:
    # Set permissions for anonymous role.
    user.role.anonymous:
      ensure_exists:
        id: anonymous
      grantPermissions:
        - 'access_unpublished node event'
    # Set permissions for content editor role.
    user.role.content_editor:
      ensure_exists:
        id: content_editor
      grantPermissions:
        - 'access_unpublished node event'
        - 'clone event content'
        - 'create event content'
        - 'create terms in event_category'
        - 'delete own event content'
        - 'delete event revisions'
        - 'edit any event content'
        - 'edit own event content'
        - 'edit terms in event_category'
        - 'revert event revisions'
        - 'set event published on date'
        - 'view any unpublished event content'
        - 'view event revisions'
